### ISSUE TITLE
Order in extracted chunk undefined - css_modules

### ISSUE THREAD

**Issue by zoeabryant** [redbadger/website-honestly#128]
```
ERROR in ./site/components/header/style.css
Order in extracted chunk undefined

ERROR in ./site/components/footer/style.css
Order in extracted chunk undefined
```

Caused by [this line](https://github.com/redbadger/website-honestly/blob/de1094782390ab104013c77458084ad1063abc75/site/pages/home/contact-us-slice/success/style.css#L11) 

[One suggested fix here](https://github.com/css-modules/css-modules/issues/12#issuecomment-165227881) on css_module's issues. Basically says import from one file, not multiple, as we cannot guarantee the order things get imported in.

**Comment by tabazevedo** [comment]
Could we potentially have a `css/index.css` where we import all the stuff in _colors.css, _fonts.css etc. and expose it in one place? Essentially what that issue suggests doing, but more manual.

**Comment by Roisi** [comment]
@asavin bit of a loss with this one

**Comment by asavin** [comment]
I'd say it's a low priority issue, most likely related to this:

`Note that composing should not form a circular dependency. Elsewise it's undefined whether properties of a rule override properties of a composed rule. The module system may emit an error.`
https://github.com/css-modules/css-modules#dependencies

**Comment by grahammendick** [comment]
The solution suggested by @tabazevedo works. Here are the steps:

* Created a _style.css in the css folder and copied all the styles from the separate files in the css folder (including _fonts.css) into there
* Put all the value definitions at the top and the class definitions at the bottom
* Deleted all `@value ... from ...` from _style.css because all references are local now
* Deleted all `composes ... from ...` from _style.css because all references are local now
* Globally replaced all references to common css files, e.g, replaced _colors.css with _style.css

And here’s the screen print showing that all ‘Order in extracted chunk undefined’ errors have gone from website honestly (only website-next ones left). It also shows that a bit of the site correctly styled.

<img width="1084" alt="screen shot 2017-03-01 at 15 42 24" src="https://cloud.githubusercontent.com/assets/1761227/23468138/e2e58966-fe97-11e6-951f-7e5448e68435.png">

If we don't like all the styles in one file then we could look at the [PostCss import plugin](https://github.com/css-modules/css-modules/issues/12#issuecomment-165227881)

**Comment by jaredh159** [comment]
Adding the `ignoreOrder: true` flag fixed the issue for us:

```ES6
const extract = new ExtractTextPlugin({
  filename: 'css/app.css',
  allChunks: true,
  ignoreOrder: true, // <-- add this ¯\_(ツ)_/¯
});
```

**Comment by markholland** [comment]
Likely addressed in [commit](https://github.com/redbadger/website-honestly/commit/3a97ea4e2215dcd0b06581a54ed5a7e8b372fa52)
