### ISSUE TITLE
Open page (background content) shouldn't be screen-readable when mobile nav is open

### ISSUE THREAD

**Issue by samsmith1983** [redbadger/website-honestly#325]
Split this one from #171. We've fixed the scrolling, but the background content is still screen-readable when the mobile nav is open.

Repro:

- Grab an iPhone
- Turn on Voiceover (Settings -> General -> Accessibility)
- Go to red-badger.com
- Click in visible bit of text in background

It's read out to you. It shouldn't be selectable.

**Comment by grahammendick** [comment]
@asavin @dstodolny There are two issues to do with the background content when the small nav is open: It shouldn’t be scrollable and it shouldn’t be (screen) readable.

The fix put in for the first (#171) was to prevent scrolling when the small nav is open. The problem with this is that it prevents the small nav menu from scrolling, so some menu items might be unreachable.

I think there’s a different fix we could try that will fix both the issues together. **When the small navigation window is open we hide the background**. Because the background’s hidden, it won’t be scrollable or (screen) readable. What do you think?

**Comment by dstodolny** [comment]
If it works it's better. My fix is a little bit hacky.

**Comment by grahammendick** [comment]
It doesn’t work. The small nav menu slides out so how we can't hide the background during the animation.

**Comment by gregdorward** [comment]
Still an issue

**Comment by dstodolny** [comment]
This is fixed now
