### ISSUE TITLE
Blogs not opening in a new tab

### ISSUE THREAD

**Issue by HarriA** [redbadger/website-honestly#414]
As a user
I want to be able to open blogs from the search results page in a new tab
So that I can continue to browse through the search results and find what I'm looking for, without disruption.

Use search on the blogs page and search for "process"
Right click on any blog in the search results page - no option to open in a new tab

**Comment by chris-brookes** [comment]
This is due to the search function and results using JS. (see similar issue #416 ) 

The JS enters the link into the code of the page as a data-url (eg. data-url="/blog/2014/09/17/badger-academy-week-3"), not a normal href link. Therefore browsers must not give these links the same options (eg. open page in a new tab) as a normal link.

We may need to show these search results in a different way to see the 'open in new tab' browser option.
