### ISSUE TITLE
Incorrect tiles shown on case-study pages

### ISSUE THREAD

**Issue by chris-brookes** [redbadger/website-honestly#440]
**Description of the issue:**
On the case-study pages there is a tile container with links to other case-studies. Sometimes it shows links to the page you are currently viewing. eg. When you view the F&M case-study page in mobile view, the only tile shown is one with links to the F&M page you are already on.

We need to make sure none of the links shown are for the case-study page you are currently on.

We need to create an extra (4th) case-study tile to fill any gaps if one of the other tiles need to be removed.

**Comment by gregdorward** [comment]
**As a website user** viewing an individual case study page
**I want** to be able to see links to 3 other case studies on the page (div is already in place)
**So that** I can view other case studies by clicking on them

Acceptance criteria

- The case studies listed must be different to the case study the user is on. i.e. do not display the link to the Retailer case study if the user is in the Retailer case study

- On desktop, 3 case studies must be displayed at all times

- On tablet, 2 case studies must be displayed at all times

- On mobile, 1 case study must be displayed at all times
