### ISSUE TITLE
Image flash when javascript disabled

### ISSUE THREAD

**Issue by markholland** [redbadger/website-honestly#650]
**Description of the issue:**

With javascript disabled the red badger logo will sometimes flash full screen on page loads.

**Browser used:** Firefox 57
**OS used:** macOS 10.13
**Device used:** MacBook Pro

**Steps to reproduce:**

1. Disable javascript in your browser
2. Go to red-badger.com
3. Observe the image briefly showing full screen on each page load

**Comment by davidbasalla** [comment]
Hey @markholland, could you have a look if this is still an issue for you? I've not been able to reproduce it, but there have been changes to the webpack config since this issue got logged.

See https://github.com/redbadger/website-honestly/pull/655 and https://github.com/redbadger/website-honestly/pull/668

**Comment by markholland** [comment]
No longer applies
